### PR TITLE
Fix #199 by adding new repo url https://s01.oss.sonatype.org to sonatype repo list

### LINKED ISSUE #199: Support new OSSRH repository
**Is your feature request related to a problem? Please describe.**
When I use maven-settings-action@2.5.0 in my project to generate settings.xml then to publish libs to Maven Central, as my project depends  on another lib I published to the snapshot repository.  The maven complains it cannot download it b/c https://s01.oss.sonatype.org/ is not in the repository list. 

According to https://central.sonatype.org/publish/publish-guide/#releasing-to-central, 

> Note: As of February 2021, all new projects began being provisioned on https://s01.oss.sonatype.org/. 

so `sonatypeSnapshots: true` will add **https://oss.sonatype.org/** but not the new repo **https://s01.oss.sonatype.org/** to the repository list, and they are not same in my experience.

**Describe the solution you'd like**
I propose a new configuration works like the old `sonatypeSnapshots: true`, assume we name it `ossrhSnapshots: true`,  to add the new repository url in the list.  

There is maybe another way to do it.  With the configuration `sonatypeSnapshots: true`, just add the new repository url to the list, then they both in the list, the only thing need the users to do is to configure the server id.

**Describe alternatives you've considered**
I tried use a custom settings.xml in my source repo, then use `mvn deploy -s ${GITHUB_WORKSPACE}/.github/workflows/settings.xml` 。

**Additional context**
noop

### PR DESCRIPTION
**Pull request by georgecao**
Support new OSSRH snapshot repo url by adding it directly to the repo list.  #199

### CODE REVIEW

**Comment by georgecao** [comment]
@slawekjaranowski PTAL

**Comment by slawekjaranowski** [comment]
Pleas fix `FAIL ./index.test.js`

**Comment by georgecao** [comment]
> Pleas fix `FAIL ./index.test.js`

It's done.

**Comment by georgecao** [comment]
@slawekjaranowski PTAL

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
@georgecao thanks

**Pull request merged**
