### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by Romanticoseu**
In some scenarios, we need proxy.

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Please don't add node_modules to git repository

**Comment by Romanticoseu** [comment]
Sorry, because we have used my fork repo to run workflow, node_modules must be added.I will delete it.

**Comment by slawekjaranowski** [comment]
Please fix tests ...
New test for new feature will be also appreciated

**Comment by slawekjaranowski** [comment]
@Romanticoseu kindly ping

**Comment by Romanticoseu** [comment]
@slawekjaranowski I hava passed all tests. Please check it.

**Comment by slawekjaranowski** [comment]
Great, thanks - code looks ok for me.

Last request - please add example to README as are for other options.

**Comment by Romanticoseu** [comment]
I have add example to README.
Do I need to run ./update-readme.sh?

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
> I have add example to README. Do I need to run ./update-readme.sh?

Thanks. 

`./update-readme.sh` is used during release prepare - You need not to execute it.

**Pull request merged**
